apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: ml-engine-pod-kill
  namespace: tradersapp
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - tradersapp
    labelSelectors:
      app: ml-engine
  duration: "60s"
