apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: bff-to-ml-engine-delay
  namespace: tradersapp
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - tradersapp
    labelSelectors:
      app: bff
  target:
    mode: all
    selector:
      namespaces:
        - tradersapp
      labelSelectors:
        app: ml-engine
  direction: to
  delay:
    latency: "150ms"
    correlation: "25"
    jitter: "25ms"
  duration: "120s"
