apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kafka-broker-pod-kill
  namespace: tradersapp
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - tradersapp
    labelSelectors:
      app: kafka
  duration: "90s"
