apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: redis-failover-pod-kill
  namespace: tradersapp
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - tradersapp
    labelSelectors:
      app: redis
  duration: "45s"
