#!/bin/bash
# Generate SBOM (Software Bill of Materials) for container images
# Usage: ./scripts/generate-sbom.sh <image> [--output-dir ./sbom]
# Dependencies: Trivy or Syft

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUTPUT_DIR="${PROJECT_ROOT}/sbom"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Parse arguments
IMAGE=""
FORMAT="spdx-json"
TOOL="trivy"

while [[ $# -gt 0 ]]; do
    case $1 in
        --image|-i)
            IMAGE="$2"
            shift 2
            ;;
        --output-dir|-o)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        --format|-f)
            FORMAT="$2"
            shift 2
            ;;
        --tool|-t)
            TOOL="$2"
            shift 2
            ;;
        --help|-h)
            echo "Usage: $0 --image <image> [options]"
            echo ""
            echo "Options:"
            echo "  --image <image>         Container image to scan (required)"
            echo "  --output-dir <dir>     Output directory [default: ./sbom]"
            echo "  --format <format>      SBOM format [default: spdx-json]"
            echo "                          Options: spdx-json, spdx-tag, cyclonedx-json"
            echo "  --tool <tool>          Tool to use [default: trivy]"
            echo "                          Options: trivy, syft"
            echo "  --help                 Show this help"
            echo ""
            echo "Examples:"
            echo "  $0 --image ghcr.io/tradersapp/ml-engine:latest"
            echo "  $0 --image ghcr.io/tradersapp/bff:latest --format cyclonedx-json"
            echo "  $0 --image ghcr.io/tradersapp/ml-engine:latest --tool syft"
            exit 0
            ;;
        -*)
            echo "Unknown option: $1"
            exit 1
            ;;
        *)
            IMAGE="$1"
            shift
            ;;
    esac
done

# Validate arguments
if [[ -z "$IMAGE" ]]; then
    echo -e "${RED}Error: Image is required${NC}"
    echo "Usage: $0 --image <image>"
    exit 1
fi

# Create output directory
mkdir -p "${OUTPUT_DIR}"

# Extract image name for filename
IMAGE_NAME=$(echo "$IMAGE" | sed 's/[:\/]/_/g' | sed 's/@sha.*$//')
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
OUTPUT_FILE="${OUTPUT_DIR}/${IMAGE_NAME}_${TIMESTAMP}.${FORMAT##*:}.json"

echo -e "${BLUE}============================================${NC}"
echo -e "${BLUE}SBOM Generator${NC}"
echo -e "${BLUE}============================================${NC}"
echo -e "Image: ${IMAGE}"
echo -e "Format: ${FORMAT}"
echo -e "Tool: ${TOOL}"
echo -e "Output: ${OUTPUT_FILE}"
echo ""

# Generate SBOM based on tool
case $TOOL in
    trivy)
        echo -e "${YELLOW}Generating SBOM with Trivy...${NC}"

        # Check if Trivy is installed
        if ! command -v trivy &> /dev/null; then
            echo -e "${YELLOW}Trivy not found, installing...${NC}"
            if [[ "$OSTYPE" == "darwin"* ]]; then
                brew install trivy
            else
                curl -sfL https://aquasecurity.github.io/trivy/v0.50.0/install.sh | sh -s -- -b /usr/local/bin
            fi
        fi

        # Run Trivy SBOM generation
        trivy image \
            --format ${FORMAT} \
            --output "${OUTPUT_FILE}" \
            --only-fixed \
            --no-progress \
            "$IMAGE"
        ;;
    syft)
        echo -e "${YELLOW}Generating SBOM with Syft...${NC}"

        # Check if Syft is installed
        if ! command -v syft &> /dev/null; then
            echo -e "${YELLOW}Syft not found, installing...${NC}"
            if [[ "$OSTYPE" == "darwin"* ]]; then
                brew install syft
            else
                curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
            fi
        fi

        # Run Syft SBOM generation
        syft packages "$IMAGE" \
            -o ${FORMAT} \
            --file "${OUTPUT_FILE}"
        ;;
    *)
        echo -e "${RED}Unknown tool: $TOOL${NC}"
        exit 1
        ;;
esac

echo ""
echo -e "${GREEN}✅ SBOM generated successfully${NC}"
echo -e "File: ${OUTPUT_FILE}"
echo ""

# Print summary
echo -e "${BLUE}SBOM Summary:${NC}"
echo ""

case $FORMAT in
    spdx-json|cyclonedx-json)
        if command -v jq &> /dev/null; then
            PACKAGE_COUNT=$(jq -r '.packages | length' "${OUTPUT_FILE}" 2>/dev/null || echo "N/A")
            echo -e "Total packages: ${PACKAGE_COUNT}"

            if [[ "$FORMAT" == "spdx-json" ]]; then
                CREATED_BY=$(jq -r '.creationInfo.name' "${OUTPUT_FILE}" 2>/dev/null || echo "N/A")
                echo -e "Generated by: ${CREATED_BY}"
            fi
        fi
        ;;
    *)
        echo -e "Format: ${FORMAT}"
        ;;
esac

echo ""
echo -e "${BLUE}SBOM files in ${OUTPUT_DIR}:${NC}"
ls -la "${OUTPUT_DIR}"/*.json 2>/dev/null | head -10 || echo "No files found"

echo ""
echo -e "${BLUE}============================================${NC}"
echo -e "${GREEN}SBOM generation complete${NC}"
echo -e "${BLUE}============================================${NC}"
