from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_TODO_PATH = ROOT / "docs" / "TODO_MASTER_LIST.md"
PROGRESS_START = "<!-- progress:start -->"
PROGRESS_END = "<!-- progress:end -->"
STATUS_SCORE = {
    "Done": 1.0,
    "Partial": 0.5,
    "Todo": 0.0,
}


@dataclass
class Task:
    phase: str
    task_id: int
    status: str
    estimate_raw: str
    estimate_min_days: float
    estimate_max_days: float


def parse_estimate_days(value: str) -> tuple[float, float]:
    text = value.strip().lower()
    if not text or text == "0d":
        return 0.0, 0.0

    match = re.fullmatch(r"(?P<min>\d+(?:\.\d+)?)(?:-(?P<max>\d+(?:\.\d+)?))?d", text)
    if not match:
        return 0.0, 0.0

    min_days = float(match.group("min"))
    max_days = float(match.group("max") or match.group("min"))
    return min_days, max_days


def parse_tasks(markdown: str) -> list[Task]:
    tasks: list[Task] = []
    current_phase = "Unscoped"

    for line in markdown.splitlines():
        phase_match = re.match(r"^###\s+(Phase\s+\d+:\s+.+)$", line.strip())
        if phase_match:
            current_phase = phase_match.group(1)
            continue

        if not line.startswith("|"):
            continue

        columns = [column.strip() for column in line.strip().strip("|").split("|")]
        if not columns or not columns[0].isdigit():
            continue

        task_id = int(columns[0])
        status = columns[1]
        estimate_raw = columns[-1]
        min_days, max_days = parse_estimate_days(estimate_raw)
        tasks.append(
            Task(
                phase=current_phase,
                task_id=task_id,
                status=status,
                estimate_raw=estimate_raw,
                estimate_min_days=min_days,
                estimate_max_days=max_days,
            )
        )

    return tasks


def format_pct(value: float) -> str:
    return f"{value:07.3f}%"


def format_days(value: float) -> str:
    return f"{value:07.3f}d"


def make_bar(percent: float, width: int = 40) -> str:
    clamped = max(0.0, min(100.0, percent))
    filled = round((clamped / 100.0) * width)
    return "[" + ("#" * filled) + ("-" * (width - filled)) + "]"


def format_count(value: float) -> str:
    return f"{int(value):03d}"


def summarize(tasks: list[Task]) -> tuple[str, dict[str, dict[str, float]]]:
    total = len(tasks)
    done = sum(1 for task in tasks if task.status == "Done")
    partial = sum(1 for task in tasks if task.status == "Partial")
    todo = sum(1 for task in tasks if task.status == "Todo")
    weighted_done = sum(STATUS_SCORE.get(task.status, 0.0) for task in tasks)
    completion_pct = (weighted_done / total * 100.0) if total else 0.0
    remaining_pct = 100.0 - completion_pct
    remaining_min_days = sum(task.estimate_min_days for task in tasks if task.status != "Done")
    remaining_max_days = sum(task.estimate_max_days for task in tasks if task.status != "Done")
    remaining_mid_days = (remaining_min_days + remaining_max_days) / 2.0
    remaining_conservative_days = remaining_min_days + ((remaining_max_days - remaining_min_days) * 0.90)

    per_phase: dict[str, dict[str, float]] = {}
    for task in tasks:
        phase = per_phase.setdefault(
            task.phase,
            {
                "total": 0.0,
                "done": 0.0,
                "partial": 0.0,
                "todo": 0.0,
                "weighted_done": 0.0,
                "remaining_min_days": 0.0,
                "remaining_max_days": 0.0,
            },
        )
        phase["total"] += 1
        phase[task.status.lower()] += 1
        phase["weighted_done"] += STATUS_SCORE.get(task.status, 0.0)
        if task.status != "Done":
            phase["remaining_min_days"] += task.estimate_min_days
            phase["remaining_max_days"] += task.estimate_max_days

    timestamp = datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S %Z")
    lines = [
        PROGRESS_START,
        "_Progress block is generated by `python scripts/update_todo_progress.py`._",
        "",
        "## Live Progress",
        "",
        f"Last sync: `{timestamp}`",
        "",
        "```text",
        "PROJECT STATUS",
        f"Complete      {format_pct(completion_pct)}  {make_bar(completion_pct, width=28)}",
        f"Remaining     {format_pct(remaining_pct)}  {make_bar(remaining_pct, width=28)}",
        f"Tasks         done {done:03d} | in progress {partial:03d} | not started {todo:03d} | total {total:03d}",
        f"Time left     likely {format_days(remaining_mid_days)}",
        f"Range         best case {format_days(remaining_min_days)} | conservative {format_days(remaining_conservative_days)} | max {format_days(remaining_max_days)}",
        "```",
        "",
        "How to read the time left:",
        f"- `likely` = the current midpoint estimate for all unfinished work: `{format_days(remaining_mid_days)}`",
        f"- `best case` = if the unfinished tasks land near their low-end estimates: `{format_days(remaining_min_days)}`",
        f"- `conservative` = a safer planning number to use: `{format_days(remaining_conservative_days)}`",
        "",
        "### Phase Progress",
        "",
        "| Phase | Progress | Status | Likely Left |",
        "|---|---:|---|---:|",
    ]

    for phase_name, data in per_phase.items():
        phase_total = data["total"]
        phase_pct = (data["weighted_done"] / phase_total * 100.0) if phase_total else 0.0
        phase_min = data["remaining_min_days"]
        phase_max = data["remaining_max_days"]
        phase_mid = (phase_min + phase_max) / 2.0
        lines.append(
            "| "
            + " | ".join(
                [
                    phase_name,
                    format_pct(phase_pct),
                    f"`{make_bar(phase_pct, width=18)}` {format_count(data['done'])}/{format_count(int(phase_total))} done",
                    format_days(phase_mid),
                ]
            )
            + " |"
        )

    lines.extend(["", PROGRESS_END])
    return "\n".join(lines), per_phase


def build_updated_markdown(todo_path: Path) -> str:
    markdown = todo_path.read_text(encoding="utf-8")
    tasks = parse_tasks(markdown)
    block, _ = summarize(tasks)

    pattern = re.compile(
        rf"{re.escape(PROGRESS_START)}.*?{re.escape(PROGRESS_END)}",
        re.DOTALL,
    )
    updated = pattern.sub(block, markdown, count=1)
    return updated + ("" if updated.endswith("\n") else "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Update docs/TODO_MASTER_LIST.md progress bars.")
    parser.add_argument(
        "--file",
        type=Path,
        default=DEFAULT_TODO_PATH,
        help="Path to the TODO markdown file.",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print the updated markdown instead of writing the file.",
    )
    parser.add_argument(
        "--block-stdout",
        action="store_true",
        help="Print only the generated progress block.",
    )
    args = parser.parse_args()
    todo_path = args.file.resolve()
    markdown = todo_path.read_text(encoding="utf-8")
    tasks = parse_tasks(markdown)
    block, _ = summarize(tasks)
    updated_markdown = build_updated_markdown(todo_path)
    if args.block_stdout:
        print(block, end="")
        return
    if args.stdout:
        print(updated_markdown, end="")
        return
    todo_path.write_text(updated_markdown, encoding="utf-8")
    print(f"Updated progress block in {args.file}")


if __name__ == "__main__":
    main()
