controller:
  kind: DaemonSet
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  watchIngressWithoutClass: false
  allowSnippetAnnotations: true
  publishService:
    enabled: false
  service:
    enabled: false
  admissionWebhooks:
    enabled: false
  metrics:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 90Mi
    limits:
      cpu: 200m
      memory: 256Mi

defaultBackend:
  enabled: false
